description: Example Mind Evolution experiment configuration
evaluator_config: {}
evaluator_type: simple
llm_model: gpt-4
llm_provider: openai
max_runtime_minutes: null
mind_evolution:
  N_candidate: 15
  N_convs: 5
  N_emigrate: 5
  N_gens: 10
  N_island: 4
  N_parent: 5
  N_reset: 2
  N_reset_interval: 3
  N_seq: 4
  N_top: 5
  Pr_no_parents: 0.16666666666666666
  checkpoint_frequency: 1
  early_stopping: true
  enable_critic: true
  enable_feedback: true
  log_level: INFO
  max_retries: 5
  model_name: gemini-1.5-flash-001
  save_all_solutions: true
  temperature: 1.0
  use_llm_for_reset: true
name: example_experiment
output_format: json
problem_config: {}
problem_type: general
random_seed: null
save_conversations: true
save_solutions: true
save_statistics: true
